PREFIX lemon: <https://ns.nkllon.com/words/v1/>
SELECT ?flow ?from ?to ?amount ?gradient
WHERE {
  ?flow a lemon:EnergyFlow ;
        lemon:from ?from ;
        lemon:to ?to ;
        lemon:flowAmount ?amount ;
        lemon:followsGradientOf ?gradient .
}
